### ISSUE TITLE
Help command refers to hard-coded path

### ISSUE THREAD

**Issue by Symbolics** [incjung/cl-maprcli#1]
In cl-maprcli.lisp, the path for help tries to load a file from a hard-coded pathname:

(cl-json:decode-json-from-source #p"~/development/swagger/cl-swagger-codegen/mapr.json")))

I suggest using a logical pathname for the project. There may also be an issue with dependencies, as cl-swagger-codegen is not loadable by ASDF.

**Comment by incjung** [comment]
changed with relative path
